# import psycopg2
# import os

from core.base_agent import BaseToolAgent
from core.tool_function import tool_function
from decimal import Decimal


class DatabaseService(BaseToolAgent):

    def __init__(self):
        super().__init__()
        # self.connection = psycopg2.connect(os.getenv("DATABASE_URL"))
        # self.cursor = self.connection.cursor()

    @tool_function(
        name="get_last_order_by_master_slug",
        description="Retrieve the most recent order placed with a master, using the master's slug identifier.",
        parameters={
            "slug": {
                "type": "string",
                "description": "Unique slug identifier of the master",
            }
        },
    )
    def get_last_order_by_master_slug(self, slug: str):
        # self.cursor.execute("...")
        # return {"count": self.cursor.fetchone()[0]}

        return "11.05.2025"

    @tool_function(
        name="get_monthly_order_count_by_master_slug",
        description="Get the number of orders completed by a specific master in a given month, using the master's slug.",
        parameters={
            "slug": {
                "type": "string",
                "description": "Unique slug identifier of the master",
            },
            "year": {
                "type": "integer",
                "description": "Year in YYYY format (e.g., 2024)",
            },
            "month": {
                "type": "integer",
                "description": "Month as a number (1 to 12)",
            },
        },
    )
    def get_monthly_order_count_by_master_slug(self, slug: str, year: int, month: int):
        # self.cursor.execute("...")
        # return {"count": self.cursor.fetchone()[0]}

        return 100

    @tool_function(
        name="get_monthly_revenue_by_master_slug",
        description=(
            "Get the total revenue generated by a specific master in a given month, identified by "
            "their slug. The returned amount is in Belarusian rubles (BYN)."
        ),
        parameters={
            "slug": {
                "type": "string",
                "description": "Unique slug identifier of the master",
            },
            "year": {
                "type": "integer",
                "description": "Year in YYYY format (e.g., 2024)",
            },
            "month": {
                "type": "integer",
                "description": "Month as a number (1 to 12)",
            },
        },
    )
    def get_monthly_revenue_by_master_slug(self, slug: str, year: int, month: int):
        # self.cursor.execute("...")
        # return {"count": self.cursor.fetchone()[0]}

        return Decimal(10000.00)
